# Scalers & Vectors

In [1]:
'''
Scaler is single number, denoted as x
Vector is array of scalers, and always a column vector
'''

'\nScaler is single number, denoted as x\nVector is array of scalers, and always a column vector\n'

In [3]:
import numpy as np

x= np.array([[4], [5], [3]])
print(x)
print(x.shape)

[[4]
 [5]
 [3]]
(3, 1)


# Matrix and Tensor

In [4]:
# Tensor means a array with more than 2 axes

In [8]:
x = np.array([[4,5,7, 8], 
              [10,11,13, 15], 
              [56,80,90, 99]])

In [9]:
print(x.shape)

(3, 4)


In [15]:
# Transpose
x = x.reshape(12, -1)
print(x) 
# x1 = x.T   # Transpose
x1 = np.transpose(x)
print(x1)

[[ 4]
 [ 5]
 [ 7]
 [ 8]
 [10]
 [11]
 [13]
 [15]
 [56]
 [80]
 [90]
 [99]]
[[ 4  5  7  8 10 11 13 15 56 80 90 99]]


In [11]:
# Transpose of Tensor
# Don't Run this cell
x1 = np.transpose(T, axes=(2, 0, 1))  # In axes, just write the permutations as you want

[[ 4]
 [ 5]
 [ 7]
 [ 8]
 [10]
 [11]
 [13]
 [15]
 [56]
 [80]
 [90]
 [99]]


In [16]:
# Broadcasting
# you can add a scaler to vector
x = np.array([1, 2, 3, 4])
print(x)
print(x + 4)

[1 2 3 4]
[5 6 7 8]


In [18]:
X = np.array([[10, 20, 30, 40],
             [40, 50, 60,70]])
print(X)
print(X + x)

[[10 20 30 40]
 [40 50 60 70]]
[[11 22 33 44]
 [41 52 63 74]]


In [21]:
# ELement Wise Multiplication - Hadamard product
A = np.array([[1,2], [3,4]])
B = np.array([[1,2], [3,4]])
print(A*B)

# Matrix Multiplication -> DOT product
np.dot(A,B)

[[ 1  4]
 [ 9 16]]


array([[ 7, 10],
       [15, 22]])

In [26]:
# Norms
x = np.array([3,4])
lp2 = np.linalg.norm(x)
print(lp2)

# 1st Norm
lp1 = np.linalg.norm(x, ord=1)
print(lp1)

# infinity Norm or Maximium norm
lp1 = np.linalg.norm(x, ord=np.inf)
print(lp1)

5.0
7.0
4.0


In [28]:
# Determinant
A = np.array([[1,2],
              [3,4]])

np.linalg.det(A)

-2.0000000000000004

In [32]:
# Inverse
np.linalg.inv(A)

# Pseudo Inverse 
# If matrix is invertible, then you can use it. Determinant is zero
np.linalg.pinv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [34]:
# System of equations
a = np.array([[2,3], [3,1]])
b = np.array([8, 5])
np.linalg.solve(a,b)

array([1., 2.])